export const COUNTRIES = [
  { code: "AD", dial_code: "+376", name: "Andorra" },
  { code: "AE", dial_code: "+971", name: "United Arab Emirates" },
  { code: "AF", dial_code: "+93", name: "Afghanistan" },
  { code: "AG", dial_code: "+1268", name: "Antigua and Barbuda" },
  { code: "AI", dial_code: "+1264", name: "Anguilla" },
  { code: "AL", dial_code: "+355", name: "Albania" },
  { code: "AM", dial_code: "+374", name: "Armenia" },
  { code: "AN", dial_code: "+599", name: "Netherlands Antilles" },
  { code: "AO", dial_code: "+244", name: "Angola" },
  { code: "AQ", dial_code: "+672", name: "Antarctica" },
  { code: "AR", dial_code: "+54", name: "Argentina" },
  { code: "AS", dial_code: "+1684", name: "American Samoa" },
  { code: "AT", dial_code: "+43", name: "Austria" },
  { code: "AU", dial_code: "+61", name: "Australia" },
  { code: "AW", dial_code: "+297", name: "Aruba" },
  { code: "AZ", dial_code: "+994", name: "Azerbaijan" },
  { code: "BA", dial_code: "+387", name: "Bosnia and Herzegovina" },
  { code: "BB", dial_code: "+1246", name: "Barbados" },
  { code: "BD", dial_code: "+880", name: "Bangladesh" },
  { code: "BE", dial_code: "+32", name: "Belgium" },
  { code: "BF", dial_code: "+226", name: "Burkina Faso" },
  { code: "BG", dial_code: "+359", name: "Bulgaria" },
  { code: "BH", dial_code: "+973", name: "Bahrain" },
  { code: "BI", dial_code: "+257", name: "Burundi" },
  { code: "BJ", dial_code: "+229", name: "Benin" },
  { code: "BL", dial_code: "+590", name: "Saint Barthelemy" },
  { code: "BM", dial_code: "+1441", name: "Bermuda" },
  { code: "BN", dial_code: "+673", name: "Brunei Darussalam" },
  { code: "BO", dial_code: "+591", name: "Bolivia" },
  { code: "BR", dial_code: "+55", name: "Brazil" },
  { code: "BS", dial_code: "+1242", name: "Bahamas" },
  { code: "BT", dial_code: "+975", name: "Bhutan" },
  { code: "BW", dial_code: "+267", name: "Botswana" },
  { code: "BY", dial_code: "+375", name: "Belarus" },
  { code: "BZ", dial_code: "+501", name: "Belize" },
  { code: "CA", dial_code: "+1", name: "Canada" },
  { code: "CC", dial_code: "+61", name: "Cocos (Keeling) Islands" },
  {
    code: "CD",
    dial_code: "+243",
    name: "Congo, the Democratic Republic of the",
  },
  { code: "CF", dial_code: "+236", name: "Central African Republic" },
  { code: "CG", dial_code: "+242", name: "Congo" },
  { code: "CH", dial_code: "+41", name: "Switzerland" },
  { code: "CI", dial_code: "+225", name: "Cote d Ivoire" },
  { code: "CK", dial_code: "+682", name: "Cook Islands" },
  { code: "CL", dial_code: "+56", name: "Chile" },
  { code: "CM", dial_code: "+237", name: "Cameroon" },
  { code: "CN", dial_code: "+86", name: "China" },
  { code: "CO", dial_code: "+57", name: "Colombia" },
  { code: "CR", dial_code: "+506", name: "Costa Rica" },
  { code: "CU", dial_code: "+53", name: "Cuba" },
  { code: "CV", dial_code: "+238", name: "Cape Verde" },
  { code: "CX", dial_code: "+61", name: "Christmas Island" },
  { code: "CY", dial_code: "+357", name: "Cyprus" },
  { code: "CZ", dial_code: "+420", name: "Czech Republic" },
  { code: "DE", dial_code: "+49", name: "Germany" },
  { code: "DJ", dial_code: "+253", name: "Djibouti" },
  { code: "DK", dial_code: "+45", name: "Denmark" },
  { code: "DM", dial_code: "+1767", name: "Dominica" },
  { code: "DO", dial_code: "+1809", name: "Dominican Republic" },
  { code: "DZ", dial_code: "+213", name: "Algeria" },
  { code: "EC", dial_code: "+593", name: "Ecuador" },
  { code: "EE", dial_code: "+372", name: "Estonia" },
  { code: "EG", dial_code: "+20", name: "Egypt" },
  { code: "ER", dial_code: "+291", name: "Eritrea" },
  { code: "ES", dial_code: "+34", name: "Spain" },
  { code: "ET", dial_code: "+251", name: "Ethiopia" },
  { code: "FI", dial_code: "+358", name: "Finland" },
  { code: "FJ", dial_code: "+679", name: "Fiji" },
  { code: "FK", dial_code: "+500", name: "Falkland Islands (Malvinas)" },
  { code: "FM", dial_code: "+691", name: "Micronesia, Federated States of" },
  { code: "FO", dial_code: "+298", name: "Faroe Islands" },
  { code: "FR", dial_code: "+33", name: "France" },
  { code: "GA", dial_code: "+241", name: "Gabon" },
  { code: "GB", dial_code: "+44", name: "United Kingdom" },
  { code: "GD", dial_code: "+1473", name: "Grenada" },
  { code: "GE", dial_code: "+995", name: "Georgia" },
  { code: "GH", dial_code: "+233", name: "Ghana" },
  { code: "GI", dial_code: "+350", name: "Gibraltar" },
  { code: "GL", dial_code: "+299", name: "Greenland" },
  { code: "GM", dial_code: "+220", name: "Gambia" },
  { code: "GN", dial_code: "+224", name: "Guinea" },
  { code: "GQ", dial_code: "+240", name: "Equatorial Guinea" },
  { code: "GR", dial_code: "+30", name: "Greece" },
  { code: "GT", dial_code: "+502", name: "Guatemala" },
  { code: "GU", dial_code: "+1671", name: "Guam" },
  { code: "GW", dial_code: "+245", name: "Guinea-Bissau" },
  { code: "GY", dial_code: "+592", name: "Guyana" },
  { code: "HK", dial_code: "+852", name: "Hong Kong" },
  { code: "HN", dial_code: "+504", name: "Honduras" },
  { code: "HR", dial_code: "+385", name: "Croatia" },
  { code: "HT", dial_code: "+509", name: "Haiti" },
  { code: "HU", dial_code: "+36", name: "Hungary" },
  { code: "ID", dial_code: "+62", name: "Indonesia" },
  { code: "IE", dial_code: "+353", name: "Ireland" },
  { code: "IL", dial_code: "+972", name: "Israel" },
  { code: "IM", dial_code: "+44", name: "Isle of Man" },
  { code: "IN", dial_code: "+91", name: "India" },
  { code: "IQ", dial_code: "+964", name: "Iraq" },
  { code: "IR", dial_code: "+98", name: "Iran, Islamic Republic of" },
  { code: "IS", dial_code: "+354", name: "Iceland" },
  { code: "IT", dial_code: "+39", name: "Italy" },
  { code: "JM", dial_code: "+1876", name: "Jamaica" },
  { code: "JO", dial_code: "+962", name: "Jordan" },
  { code: "JP", dial_code: "+81", name: "Japan" },
  { code: "KE", dial_code: "+254", name: "Kenya" },
  { code: "KG", dial_code: "+996", name: "Kyrgyzstan" },
  { code: "KH", dial_code: "+855", name: "Cambodia" },
  { code: "KI", dial_code: "+686", name: "Kiribati" },
  { code: "KM", dial_code: "+269", name: "Comoros" },
  { code: "KN", dial_code: "+1869", name: "Saint Kitts and Nevis" },
  {
    code: "KP",
    dial_code: "+850",
    name: "Korea Democratic Peoples Republic of",
  },
  { code: "KR", dial_code: "+82", name: "Korea Republic of" },
  { code: "KW", dial_code: "+965", name: "Kuwait" },
  { code: "KY", dial_code: "+1345", name: "Cayman Islands" },
  { code: "KZ", dial_code: "+7", name: "Kazakstan" },
  { code: "LA", dial_code: "+856", name: "Lao Peoples Democratic Republic" },
  { code: "LB", dial_code: "+961", name: "Lebanon" },
  { code: "LC", dial_code: "+1758", name: "Saint Lucia" },
  { code: "LI", dial_code: "+423", name: "Liechtenstein" },
  { code: "LK", dial_code: "+94", name: "Sri Lanka" },
  { code: "LR", dial_code: "+231", name: "Liberia" },
  { code: "LS", dial_code: "+266", name: "Lesotho" },
  { code: "LT", dial_code: "+370", name: "Lithuania" },
  { code: "LU", dial_code: "+352", name: "Luxembourg" },
  { code: "LV", dial_code: "+371", name: "Latvia" },
  { code: "LY", dial_code: "+218", name: "Libyan Arab Jamahiriya" },
  { code: "MA", dial_code: "+212", name: "Morocco" },
  { code: "MC", dial_code: "+377", name: "Monaco" },
  { code: "MD", dial_code: "+373", name: "Moldova, Republic of" },
  { code: "ME", dial_code: "+382", name: "Montenegro" },
  { code: "MF", dial_code: "+1599", name: "Saint Martin" },
  { code: "MG", dial_code: "+261", name: "Madagascar" },
  { code: "MH", dial_code: "+692", name: "Marshall Islands" },
  {
    code: "MK",
    dial_code: "+389",
    name: "Macedonia, the Former Yugoslav Republic of",
  },
  { code: "ML", dial_code: "+223", name: "Mali" },
  { code: "MM", dial_code: "+95", name: "Myanmar" },
  { code: "MN", dial_code: "+976", name: "Mongolia" },
  { code: "MO", dial_code: "+853", name: "Macau" },
  { code: "MP", dial_code: "+1670", name: "Northern Mariana Islands" },
  { code: "MR", dial_code: "+222", name: "Mauritania" },
  { code: "MS", dial_code: "+1664", name: "Montserrat" },
  { code: "MT", dial_code: "+356", name: "Malta" },
  { code: "MU", dial_code: "+230", name: "Mauritius" },
  { code: "MV", dial_code: "+960", name: "Maldives" },
  { code: "MW", dial_code: "+265", name: "Malawi" },
  { code: "MX", dial_code: "+52", name: "Mexico" },
  { code: "MY", dial_code: "+60", name: "Malaysia" },
  { code: "MZ", dial_code: "+258", name: "Mozambique" },
  { code: "NA", dial_code: "+264", name: "Namibia" },
  { code: "NC", dial_code: "+687", name: "New Caledonia" },
  { code: "NE", dial_code: "+227", name: "Niger" },
  { code: "NG", dial_code: "+234", name: "Nigeria" },
  { code: "NI", dial_code: "+505", name: "Nicaragua" },
  { code: "NL", dial_code: "+31", name: "Netherlands" },
  { code: "NO", dial_code: "+47", name: "Norway" },
  { code: "NP", dial_code: "+977", name: "Nepal" },
  { code: "NR", dial_code: "+674", name: "Nauru" },
  { code: "NU", dial_code: "+683", name: "Niue" },
  { code: "NZ", dial_code: "+64", name: "New Zealand" },
  { code: "OM", dial_code: "+968", name: "Oman" },
  { code: "PA", dial_code: "+507", name: "Panama" },
  { code: "PE", dial_code: "+51", name: "Peru" },
  { code: "PF", dial_code: "+689", name: "French Polynesia" },
  { code: "PG", dial_code: "+675", name: "Papua New Guinea" },
  { code: "PH", dial_code: "+63", name: "Philippines" },
  { code: "PK", dial_code: "+92", name: "Pakistan" },
  { code: "PL", dial_code: "+48", name: "Poland" },
  { code: "PM", dial_code: "+508", name: "Saint Pierre and Miquelon" },
  { code: "PN", dial_code: "+870", name: "Pitcairn" },
  { code: "PR", dial_code: "+1", name: "Puerto Rico" },
  { code: "PT", dial_code: "+351", name: "Portugal" },
  { code: "PW", dial_code: "+680", name: "Palau" },
  { code: "PY", dial_code: "+595", name: "Paraguay" },
  { code: "QA", dial_code: "+974", name: "Qatar" },
  { code: "RO", dial_code: "+40", name: "Romania" },
  { code: "RS", dial_code: "+381", name: "Serbia" },
  { code: "RU", dial_code: "+7", name: "Russian Federation" },
  { code: "RW", dial_code: "+250", name: "Rwanda" },
  { code: "SA", dial_code: "+966", name: "Saudi Arabia" },
  { code: "SB", dial_code: "+677", name: "Solomon Islands" },
  { code: "SC", dial_code: "+248", name: "Seychelles" },
  { code: "SD", dial_code: "+249", name: "Sudan" },
  { code: "SE", dial_code: "+46", name: "Sweden" },
  { code: "SG", dial_code: "+65", name: "Singapore" },
  { code: "SH", dial_code: "+290", name: "Saint Helena" },
  { code: "SI", dial_code: "+386", name: "Slovenia" },
  { code: "SK", dial_code: "+421", name: "Slovakia" },
  { code: "SL", dial_code: "+232", name: "Sierra Leone" },
  { code: "SM", dial_code: "+378", name: "San Marino" },
  { code: "SN", dial_code: "+221", name: "Senegal" },
  { code: "SO", dial_code: "+252", name: "Somalia" },
  { code: "SR", dial_code: "+597", name: "Suriname" },
  { code: "ST", dial_code: "+239", name: "Sao Tome and Principe" },
  { code: "SV", dial_code: "+503", name: "El Salvador" },
  { code: "SY", dial_code: "+963", name: "Syrian Arab Republic" },
  { code: "SZ", dial_code: "+268", name: "Swaziland" },
  { code: "TC", dial_code: "+1649", name: "Turks and Caicos Islands" },
  { code: "TD", dial_code: "+235", name: "Chad" },
  { code: "TG", dial_code: "+228", name: "Togo" },
  { code: "TH", dial_code: "+66", name: "Thailand" },
  { code: "TJ", dial_code: "+992", name: "Tajikistan" },
  { code: "TK", dial_code: "+690", name: "Tokelau" },
  { code: "TL", dial_code: "+670", name: "Timor-Leste" },
  { code: "TM", dial_code: "+993", name: "Turkmenistan" },
  { code: "TN", dial_code: "+216", name: "Tunisia" },
  { code: "TO", dial_code: "+676", name: "Tonga" },
  { code: "TR", dial_code: "+90", name: "Turkey" },
  { code: "TT", dial_code: "+1868", name: "Trinidad and Tobago" },
  { code: "TV", dial_code: "+688", name: "Tuvalu" },
  { code: "TW", dial_code: "+886", name: "Taiwan, Province of China" },
  { code: "TZ", dial_code: "+255", name: "Tanzania, United Republic of" },
  { code: "UA", dial_code: "+380", name: "Ukraine" },
  { code: "UG", dial_code: "+256", name: "Uganda" },
  { code: "US", dial_code: "+1", name: "United States" },
  { code: "UY", dial_code: "+598", name: "Uruguay" },
  { code: "UZ", dial_code: "+998", name: "Uzbekistan" },
  { code: "VA", dial_code: "+39", name: "Holy See (Vatican City State)" },
  { code: "VC", dial_code: "+1784", name: "Saint Vincent and the Grenadines" },
  { code: "VE", dial_code: "+58", name: "Venezuela" },
  { code: "VG", dial_code: "+1284", name: "Virgin Islands, British" },
  { code: "VI", dial_code: "+1340", name: "Virgin Islands, U.S." },
  { code: "VN", dial_code: "+84", name: "Viet Nam" },
  { code: "VU", dial_code: "+678", name: "Vanuatu" },
  { code: "WF", dial_code: "+681", name: "Wallis and Futuna" },
  { code: "WS", dial_code: "+685", name: "Samoa" },
  { code: "XK", dial_code: "+381", name: "Kosovo" },
  { code: "YE", dial_code: "+967", name: "Yemen" },
  { code: "YT", dial_code: "+262", name: "Mayotte" },
  { code: "ZA", dial_code: "+27", name: "South Africa" },
  { code: "ZM", dial_code: "+260", name: "Zambia" },
  { code: "ZW", dial_code: "+263", name: "Zimbabwe" },
];
