// styles
import "@workspace/ui/styles/globals.css";
import { Toaster } from "react-hot-toast";
import "./globals.css";
// imports
import type React from "react";
import ResponsiveLayout from "./responsive-layout";
export const dynamic = "force-dynamic";
import { ReactNode } from "react";

import Script from "next/script";
import { Metadata } from "next";
// third party
import { SidebarProvider } from "@workspace/ui/components/sidebar";
import CookieModal from "@workspace/ui/common/modal/cookies-modal/CookiesModal";

import { ToastProvider } from "@workspace/ui/common/toast/toast-context";
import { ToastContainer } from "@workspace/ui/common/toast/index";

export const metadata: Metadata = {
  title: "Casino Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/aba0ebl.css" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
        <meta name="theme-color" content="#1a2c38" />
        {/* <!-- Windows Phone --> */}
        <meta name="msapplication-navbutton-color" content="#1a2c38" />
        {/* <!-- iOS Safari --> */}
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        ></meta>
      </head>
      <body cz-shortcut-listen="true" className="relative !top-0">
        <Script src="/language/translateicon.js" strategy="afterInteractive" />
        <Script src="/language/lang-config.js" strategy="beforeInteractive" />
        <Script src="/language/translation.js" strategy="beforeInteractive" />
        <Script
          src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
          strategy="afterInteractive"
        />
        <ToastProvider>
          <SidebarProvider>
            <ResponsiveLayout>{children}</ResponsiveLayout>
            <CookieModal />
            <Toaster position="top-left" />
            <ToastContainer />
          </SidebarProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
