// styles
import "@workspace/ui/styles/globals.css";
import "./globals.css";

// imports
import type React from "react";
import { ReactNode, Suspense } from "react";
import { Metadata } from "next";
import Script from "next/script";

// third party
import { SidebarProvider } from "@workspace/ui/components/sidebar";
import { ToastProvider } from "@workspace/ui/common/toast/toast-context";
import { ToastContainer } from "@workspace/ui/common/toast/index";
import { Toaster } from "react-hot-toast";
import CookieModal from "@workspace/ui/common/modal/cookies-modal/CookiesModal";

// local
import ResponsiveLayout from "./responsive-layout";
import Loading from "./loading";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Casino Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/aba0ebl.css" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
        <meta name="theme-color" content="#1a2c38" />
        <meta name="msapplication-navbutton-color" content="#1a2c38" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
      </head>

      <body className="relative !top-0" cz-shortcut-listen="true">
        {/* 🧩 Load external scripts */}
        <Script src="/language/translateicon.js" strategy="afterInteractive" />
        <Script src="/language/lang-config.js" strategy="beforeInteractive" />
        <Script src="/language/translation.js" strategy="beforeInteractive" />
        <Script
          src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
          strategy="afterInteractive"
        />

        {/* 🧩 Wrap app with providers */}
        <ToastProvider>
          <SidebarProvider>
            {/* ✅ Suspense added here */}
            <Suspense fallback={<Loading/>}>
              <ResponsiveLayout>{children}</ResponsiveLayout>
              <CookieModal />
              <ToastContainer />
            </Suspense>

            {/* React Hot Toast works outside Suspense */}
            <Toaster position="top-left" />
          </SidebarProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
